In [1]:
#1

import numpy as np


a = np.array([1, 2, 3, 4, 5])
print(a)  # [1 2 3 4 5]


[1 2 3 4 5]


In [2]:
#2
def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a



print(what(1)) # what do these print and why?
print(what(2))
print(what(3))

1
[1 2 3 4]
2
[[1 2 3 4]]
3
[[[1 2 3 4]]]


In [3]:
#3
import numpy as np

a = np.array([1, 2, 3, 4])
print(a.ndim)  # should print 1 (refers to a)

b = np.array([[1, 2], [3, 4]])
print(b.ndim)  # should print 2 (refers to b)


1
2


In [4]:
#4
a = np.array([1, 2, 3, 4], ndmin=2)
print(a) 


[[1 2 3 4]]


In [5]:
#5
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a[4])  # should print 50 (refers to a)


50


In [6]:

#6
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a[1, 0])  # should print 50 (refers to a)


50


In [7]:

#7
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

# Print the number 50
print(a[1, 0])

50


In [8]:
#8


a = np.array([10, 20, 30, 40, 50])

# Print the last item using negative indexing
print(a[-1])

50


In [ ]:
#9
a = np.array([10, 15, 20, 25, 30, 35, 40])
result = a[1:4]
print(result)


In [ ]:
#10
import numpy as np

a = np.array([10, 15, 20, 25, 30, 35, 40])


result = a[2:4]

print(result)


In [ ]:
# 11
import numpy as np

a = np.array([10, 15, 20, 25, 30, 35, 40])


result = a[1:4:2]

print(result)  


In [9]:
#12
a = np.array([10, 15, 20, 25, 30, 35, 40])


result = a[::2]

print(result)

[10 20 30 40]


In [ ]:
#13
a = np.array([1, 2, 3])


print(a.dtype)

In [10]:
#14
a = np.array([1, 2, 3, 4], dtype='S')
print(a.dtype)
print(a[0] + a[1])
a = np.array([5, 1, -1, 3], dtype='S')
b = a.astype('i') # what happens here? 
print(b[0] + b[1] + b[3]) 
print(a[0] + a[1] + a[3])

|S1
b'12'
9
b'513'


In [11]:
#15
a = np.array([1.1, 2.1, 3.1])
b = a.astype(int)
print(b)

[1 2 3]


In [12]:
#16
a = np.array([1, 2, 3, 4, 5])
x = a.copy()
x[0] = -5
print(a) 
b = a
b[0] = -25
print(a)

[1 2 3 4 5]
[-25   2   3   4   5]


In [13]:
#17
a = np.array([1, 2, 3, 4, 5])
d = a[:]

#     then predict the effect of these expressions:

print(a.base)
print(d.base) # why is this different from all the others?
b = a
print(b.base)
c = a.copy()
print(c.base)

None
[1 2 3 4 5]
None
None


In [15]:
#18
a = np.array([1, 2, 3, 4])
print(a.shape)
a.reshape(1, 4)
print(a)
a.reshape(2, 2)
print(a)
a.reshape(4, 1)
print(a)


(4,)
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [24]:
#19
a = np.array([1, 2, 3, 4])
b=a.reshape(2,2)
a=b[:]
print(a)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)
b = a.reshape(3, 4)
print(b)



[[1 2]
 [3 4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
#20
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape(-1) # complete this statement to result in the output below
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
#21
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter? 
print(c) # what gets printed and why? 
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)? 
print(c)

[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# 22
import numpy as np

a = np.array([1, 2, 3, 4, 5, 4, 4])

# Find all items with value 4
where = np.where(a == 4)

print(where)


(array([3, 5, 6]),)


In [21]:
#23
import numpy as np

a = np.array([3, 2, 0, 1])

# Return a sorted array
b = np.sort(a)

print(b)


[0 1 2 3]
